### ISSUE TITLE
src_dir = r"C:\TestA" dst_dir = r"C:\TestB" dst1_dir = r"C:\TestC"

### ISSUE THREAD

**Issue by PieButNotThatPie** [travman1900/DroneFactoryReplacement#1]
Separate directory inputs to a new config file and pull from it?
DFR.config
> src_dir = r"C:\TestA"
> dst_dir = r"C:\TestB"
> dst1_dir = r"C:\TestC"

**Comment by travman1900** [comment]
Looking into your request....

**Comment by travman1900** [comment]
at this time the edit needs to be done inside the .py

From there you can add as a scheduled task on a windows machine to replace drone factory.

I am looking into a GUI or a config template.

**Comment by travman1900** [comment]
Please see my latest commit. this has been addressed in the config.ini
